--- #YAML:1.0
name:                genpass
version:             0.08
abstract:            Quickly create secure passwords
license:             perl
author:              
    - Sawyer X (xsawyerx@cpan.org)
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Config::General:               2.4
    File::HomeDir:                 0.82
    Getopt::Long:                  2.35
    List::MoreUtils:               0.22
    List::Util:                    1.19
    Path::Class:                   0.16
    Readonly:                      1.03
    Test::Simple:                  0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
