--- #YAML:1.0
name:                genpass
version:             0.04
abstract:            Quickly create secure passwords
license:             ~
author:              
    - Sawyer X (xsawyerx@cpan.org)
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Getopt::Long:                  2.35
    List::MoreUtils:               0.22
    Test::Simple:                  0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
